# Generated by Django 4.2.5 on 2023-10-13 13:26

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cluster', '0001_initial_migration'),
        ('common', '0001_initial_migration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('uuid', models.UUIDField(auto_created=True, blank=True, default=uuid.uuid4, editable=False, null=True, unique=True)),
                ('id', models.BigAutoField(db_index=True, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('identifier', models.CharField(db_index=True, max_length=64)),
                ('configured', models.BooleanField(default=False)),
                ('configured_at', models.DateTimeField(blank=True, null=True)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cluster.cluster')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('custom_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='DeviceCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('identifier', models.IntegerField(default=0, unique=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('default_value', models.JSONField(blank=True, null=True)),
                ('domain_switch', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceCommandRequest',
            fields=[
                ('uuid', models.UUIDField(auto_created=True, blank=True, default=uuid.uuid4, editable=False, null=True, unique=True)),
                ('id', models.BigAutoField(db_index=True, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted', models.BooleanField(default=False)),
                ('device_command_updated', models.JSONField(blank=True, null=True)),
                ('data', models.JSONField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.device')),
                ('device_command', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.devicecommand')),
                ('domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.availabledomain')),
            ],
            options={
                'ordering': ('created_at',),
            },
            managers=[
                ('custom_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='DeviceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('note', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DevicePingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('note', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DevicePing',
            fields=[
                ('uuid', models.UUIDField(auto_created=True, blank=True, default=uuid.uuid4, editable=False, null=True, unique=True)),
                ('id', models.BigAutoField(db_index=True, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted', models.BooleanField(default=False)),
                ('message', models.TextField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.device')),
                ('device_ping_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.devicepingstatus')),
            ],
            options={
                'ordering': ('-created_at',),
            },
            managers=[
                ('custom_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='DeviceFirmware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firmware_version', models.CharField(max_length=255)),
                ('firmware_note', models.TextField(blank=True, null=True)),
                ('firmware', models.FileField(upload_to='device-firmware')),
                ('device_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.devicemodel')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceCommandResponse',
            fields=[
                ('uuid', models.UUIDField(auto_created=True, blank=True, default=uuid.uuid4, editable=False, null=True, unique=True)),
                ('id', models.BigAutoField(db_index=True, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted', models.BooleanField(default=False)),
                ('response_at', models.DateTimeField(db_index=True)),
                ('applied', models.BooleanField(default=False)),
                ('response_message', models.JSONField(blank=True, null=True)),
                ('device_command_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='device_command_response', to='device.devicecommandrequest')),
            ],
            options={
                'ordering': ('-created_at',),
            },
            managers=[
                ('custom_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='devicecommand',
            name='device_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.devicemodel'),
        ),
        migrations.AddField(
            model_name='device',
            name='device_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.devicemodel'),
        ),
        migrations.AddField(
            model_name='device',
            name='firmware',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.devicefirmware'),
        ),
        migrations.AlterUniqueTogether(
            name='devicecommand',
            unique_together={('name', 'device_model')},
        ),
    ]
