# Generated by Django 4.2.5 on 2023-10-13 07:22

from django.db import migrations, models
import django.db.models.manager
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlertType',
            fields=[
                ('uuid', models.UUIDField(auto_created=True, blank=True, default=uuid.uuid4, editable=False, null=True, unique=True)),
                ('id', models.BigAutoField(db_index=True, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('persistant', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('custom_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationModuleClusterRolePermission',
            fields=[
                ('uuid', models.UUIDField(auto_created=True, blank=True, default=uuid.uuid4, editable=False, null=True, unique=True)),
                ('id', models.BigAutoField(db_index=True, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted', models.BooleanField(default=False)),
                ('read', models.BooleanField(default=False)),
                ('write', models.BooleanField(default=False)),
                ('delete', models.BooleanField(default=False)),
            ],
            managers=[
                ('custom_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('uuid', models.UUIDField(auto_created=True, blank=True, default=uuid.uuid4, editable=False, null=True, unique=True)),
                ('id', models.BigAutoField(db_index=True, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(blank=True, max_length=150, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=45, null=True)),
                ('country', models.CharField(blank=True, max_length=60, null=True)),
                ('phone', models.CharField(blank=True, max_length=35, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('external_cluster_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('active_antennas', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('custom_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ClusterMachineDevice',
            fields=[
                ('uuid', models.UUIDField(auto_created=True, blank=True, default=uuid.uuid4, editable=False, null=True, unique=True)),
                ('id', models.BigAutoField(db_index=True, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted', models.BooleanField(default=False)),
                ('domain', models.CharField(blank=True, max_length=255, null=True)),
            ],
            managers=[
                ('custom_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ClusterRole',
            fields=[
                ('uuid', models.UUIDField(auto_created=True, blank=True, default=uuid.uuid4, editable=False, null=True, unique=True)),
                ('id', models.BigAutoField(db_index=True, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted', models.BooleanField(default=False)),
            ],
            managers=[
                ('custom_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ClusterRoleAlert',
            fields=[
                ('uuid', models.UUIDField(auto_created=True, blank=True, default=uuid.uuid4, editable=False, null=True, unique=True)),
                ('id', models.BigAutoField(db_index=True, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted', models.BooleanField(default=False)),
                ('data', models.JSONField(default=dict)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('custom_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ClusterUser',
            fields=[
                ('uuid', models.UUIDField(auto_created=True, blank=True, default=uuid.uuid4, editable=False, null=True, unique=True)),
                ('id', models.BigAutoField(db_index=True, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted', models.BooleanField(default=False)),
            ],
            managers=[
                ('custom_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='UserApplicationRole',
            fields=[
                ('uuid', models.UUIDField(auto_created=True, blank=True, default=uuid.uuid4, editable=False, null=True, unique=True)),
                ('id', models.BigAutoField(db_index=True, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted', models.BooleanField(default=False)),
            ],
            managers=[
                ('custom_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='UserClient',
            fields=[
                ('uuid', models.UUIDField(auto_created=True, blank=True, default=uuid.uuid4, editable=False, null=True, unique=True)),
                ('id', models.BigAutoField(db_index=True, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted', models.BooleanField(default=False)),
            ],
            managers=[
                ('custom_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
