# Generated by Django 4.2.5 on 2023-10-13 13:26

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cluster', '0001_initial_migration'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('note', models.TextField(blank=True, null=True)),
                ('program_number', models.CharField(blank=True, max_length=255, null=True)),
                ('bar_cutter', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('uuid', models.UUIDField(auto_created=True, blank=True, default=uuid.uuid4, editable=False, null=True, unique=True)),
                ('id', models.BigAutoField(db_index=True, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('active_wires', models.IntegerField(default=1)),
                ('active_bins', models.IntegerField(blank=True, null=True)),
                ('designated_disposal_bin', models.IntegerField(blank=True, null=True)),
                ('location_designation', models.CharField(blank=True, max_length=255, null=True)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cluster.cluster')),
                ('machine_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machine.machinemodel')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('custom_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
